[bumpver]
current_version = "2021-08.1003"
version_pattern = "YYYY-0M.BUILD[-TAG]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[bumpver.file_patterns]
"bumpver.toml" = [
    'current_version = "{version}"',
]
